name: pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: guilhermelinosp/templates/.github/workflows/release.yml@latest
    with:
      app-client-id: ${{ vars.HELLNET_ACTIONS_CLIENT_ID }}
    secrets: inherit
